### ISSUE TITLE
Corrections to temp-logger-http

### ISSUE THREAD

**Issue by clixx-io** [clixx-io/clixx.io#3]
Complete the load of ini values.

sk:send("GET /logsensor/temp-logger-http?temp="..lm75:readTemp().." HTTP/1.1 \\r\\n\\r\\n")

'temp-logger-http' needs to come from the .ini file as it is the project name.

[Project]
name=temp-logger-http

**Comment by abbasraza** [comment]
@clixx-io support added in 2d8f1a57193b7312563f56056e7e2282cea7fdf0
